# Generated by Django 4.2.28 on 2026-03-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VMSBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_id', models.IntegerField(help_text='Unique board identifier (1-20)', unique=True)),
                ('vms_player_name', models.CharField(help_text='Location name where board is installed', max_length=255)),
                ('corridor_name', models.CharField(help_text='Corridor name (e.g., Karve chowk to khandoji baba)', max_length=255)),
                ('pair_id', models.IntegerField(help_text='Pair ID from Iteris dashboard')),
                ('location', models.CharField(help_text='Physical location of the board', max_length=255)),
                ('latitude', models.DecimalField(decimal_places=7, help_text='Latitude coordinate', max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, help_text='Longitude coordinate', max_digits=10)),
                ('display_time', models.CharField(help_text='Display duration (e.g., 10 seconds every 1 Min)', max_length=100)),
                ('resolution', models.CharField(default='1920x1080', help_text='Display resolution', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Is board currently operational?')),
                ('last_update', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
            ],
            options={
                'verbose_name': 'VMS Board',
                'verbose_name_plural': 'VMS Boards',
                'ordering': ['board_id'],
            },
        ),
    ]
